ifndef _INC_PYTHON_SYSTEMD
_INC_PYTHON_SYSTEMD=yes

include manifest.mk

PYTHON_SYSTEMD_VERSION?=235
PYTHON_SYSTEMD_PKGNAME=python-systemd-$(PYTHON_SYSTEMD_VERSION)
PYTHON_SYSTEMD_PKGTYPE=tar.gz
PYTHON_SYSTEMD_DIR=$(SRCDIR)/$(PYTHON_SYSTEMD_PKGNAME)
PYTHON_SYSTEMD_PKG=$(PYTHON_SYSTEMD_PKGNAME).$(PYTHON_SYSTEMD_PKGTYPE)
PYTHON_SYSTEMD_URL=https://github.com/systemd/python-systemd/archive/refs/tags/v$(PYTHON_SYSTEMD_VERSION).$(PYTHON_SYSTEMD_PKGTYPE)

$(PYTHON_SYSTEMD_PKG): | $(PKGDIR)
	wget $(PYTHON_SYSTEMD_URL) -O $(PKGDIR)/$(PYTHON_SYSTEMD_PKG)

$(PYTHON_SYSTEMD_PKGNAME)/setup.py: python | $(PYTHON_SYSTEMD_PKG) $(SRCDIR)
	tar xf $(PKGDIR)/$(PYTHON_SYSTEMD_PKG) -C $(SRCDIR)

python-systemd: $(PYTHON_SYSTEMD_PKGNAME)/setup.py
	cd $(PYTHON_SYSTEMD_DIR) && \
		python3 setup.py install

endif
